In [1]:
import numpy as np

In [2]:
# 15개의 숫자를 (3,5)차원으로 생성
arr1 = np.arange(15).reshape(3,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
# 넘파이 배열 정보 확인
print(arr1.shape) # 데이터 차원 확인
print(arr1.dtype) # 데이터 타입 확인

(3, 5)
int64


In [7]:
# 0으로 채워진 배열 생성
arr2 = np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# 넘파이 배열 생성
arr3 = np.array([[1,2,3],[4,5,6]], dtype = np.float64)
arr4 = np.array([[7,8,9],[10,11,12]], dtype = np.float64)

# 사칙연산 출력
print("arr3 + arr4 = ",'\n', arr3 + arr4,"\n")
print("arr3 - arr4 = ",'\n', arr3 - arr4,"\n")
print("arr3 * arr4 = ",'\n', arr3 * arr4,"\n")
print("arr3 / arr4 = ",'\n', arr3 / arr4,"\n")

arr3 + arr4 =  
 [[ 8. 10. 12.]
 [14. 16. 18.]] 

arr3 - arr4 =  
 [[-6. -6. -6.]
 [-6. -6. -6.]] 

arr3 * arr4 =  
 [[ 7. 16. 27.]
 [40. 55. 72.]] 

arr3 / arr4 =  
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]] 

